#!/bin/bash
# Quick Judge Demo Script
# Copy & paste sections below to evaluate the system

echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║           AI Contract Reviewer - Judge Demo Commands                       ║"
echo "║                 Ready-to-Copy Command Blocks                              ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"

echo ""
echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 1. START EVERYTHING IN ONE COMMAND                                      │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "docker-compose up --build"
echo ""
echo "↓ Wait 30-60 seconds, then try the commands below ↓"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 2. CHECK SYSTEM HEALTH                                                  │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Backend:   curl http://localhost:8000/health"
echo "MCP:       curl http://localhost:8001/health"
echo "API Docs:  Open http://localhost:8000/docs in browser"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 3. SYNCHRONOUS UPLOAD (Blocking, returns result immediately)           │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "curl -X POST http://localhost:8000/upload \\"
echo "  -F 'file=@demo/sample.mp4' | jq '.events | length'"
echo ""
echo "Expected: 6 violations detected"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 4. ASYNC WORKFLOW (Upload → Poll → Download)                           │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "# Step 1: Submit job"
echo "JOB_ID=\$(curl -s -X POST http://localhost:8000/upload_async \\"
echo "  -F 'file=@demo/sample.mp4' | jq -r '.job_id')"
echo "echo \"Job ID: \$JOB_ID\""
echo ""
echo "# Step 2: Check status (run multiple times)"
echo "curl http://localhost:8000/status/\$JOB_ID | jq '.status'"
echo ""
echo "# Step 3: Wait for 'done' status, then fetch result"
echo "curl http://localhost:8000/result/\$JOB_ID | jq '.result.events | length'"
echo ""
echo "# Step 4: Download PDF"
echo "PDF_PATH=\$(curl -s http://localhost:8000/result/\$JOB_ID | jq -r '.result.report_pdf')"
echo "curl -o /tmp/report.pdf \"http://localhost:8000/download_file?path=\$PDF_PATH\""
echo "echo \"Report saved to /tmp/report.pdf\""
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 5. VIEW AUDIT TRAIL (Immutable log of all tool calls)                  │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "# All audit entries"
echo "curl http://localhost:8001/audits | jq '.audits | length'"
echo ""
echo "# Last 5 entries"
echo "curl http://localhost:8001/audits | jq '.audits[-5:]'"
echo ""
echo "# Just detector calls"
echo "curl http://localhost:8001/audits | jq '.audits[] | select(.tool==\"run_detector\")'"
echo ""
echo "# Just reasoning calls"
echo "curl http://localhost:8001/audits | jq '.audits[] | select(.tool==\"run_vlm_reasoning\")'"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 6. STREAMLIT UI (Visual interface)                                     │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Open: http://localhost:8501"
echo ""
echo "Then:"
echo "  1. Drag & drop demo/sample.mp4 (or any video)"
echo "  2. Watch job status update in real-time"
echo "  3. Click 'Download Report' when done"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 7. INSPECT GENERATED REPORT                                            │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "# Find latest report"
echo "ls -lht /tmp/*.violation_report.pdf | head -1"
echo ""
echo "# Open report"
echo "xdg-open /tmp/*.violation_report.pdf"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 8. VALIDATE ASYNC ENDPOINT RESPONSES                                   │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "# Check upload_async response structure"
echo "curl -X POST http://localhost:8000/upload_async \\"
echo "  -F 'file=@demo/sample.mp4' | jq 'keys'"
echo ""
echo "Expected keys: [\"job_id\", \"status\"]"
echo ""
echo "# Check status response structure"
echo "curl http://localhost:8000/status/<job_id> | jq 'keys'"
echo ""
echo "Expected keys: [\"job_id\", \"progress\", \"status\"]"
echo ""
echo "# Check result response structure"
echo "curl http://localhost:8000/result/<job_id> | jq 'keys'"
echo ""
echo "Expected keys: [\"result\", \"status\"]"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 9. JUDGE SCORING CHECKLIST                                             │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "☐ Docker Compose starts without errors"
echo "☐ All 3 services healthy (check /health endpoints)"
echo "☐ Async upload returns job_id"
echo "☐ Status polling shows progress updates"
echo "☐ Result endpoint returns JSON with events array"
echo "☐ PDF report is downloadable and opens"
echo "☐ PDF contains thumbnails with bounding boxes"
echo "☐ Audit log is queryable and immutable"
echo "☐ Streamlit UI is functional and responsive"
echo "☐ End-to-end: upload → detect → log → report → download"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│ 10. TROUBLESHOOTING                                                    │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Port already in use?"
echo "  pkill -f 'uvicorn\\|streamlit'"
echo ""
echo "Docker won't build?"
echo "  docker system prune"
echo "  docker-compose up --build --no-cache"
echo ""
echo "No detections in report?"
echo "  curl http://localhost:8001/audits | jq '.audits[] | select(.tool==\"run_detector\")' | head"
echo ""
echo "PDF won't download?"
echo "  ls /tmp/*.violation_report.pdf"
echo "  (Check if file exists)"
echo ""

echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║                    Good luck with your evaluation! 🎯                     ║"
echo "║              Questions? Check JUDGE_QUICKSTART.md or README.md           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
